---
- name: Install MySql and create Database  
  hosts: databases
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root
  tasks:
  - name: Install pip
    apt:
      name: python3-pip
      state: present
  - name: Install PyMySQL
    pip:
      name: pymysql
      state: present
  - name: Install MySql
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: Create database user zakaria
    ansible.builtin.mysql_user:
      name: zakaria
      password: 12345 # best password ever
      priv: '*.*:ALL'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
  - name: Create Database test
    community.mysql.mysql_db:
      login_user: zakaria
      login_password: 12345
      login_unix_socket: /run/mysqld/mysqld.sock
      name:
        - zakariaDB
      state: present
  - name: Create a Table 
    ansible.builtin.command:
      mysql -u zakaria -p12345 -e 'CREATE TABLE Users (name varchar(30),email varchar(255));' zakariaDB
